# Resource Tagging is so important, lets start from here
resources:
  tags:
    Environment: "Development"
    Project: "Assessment"
    ManagedBy: "Terraform"
  name: "aws-ASG-PoC"

# VPC Settings
vpc:
  cidr: "10.35.0.0/16"
  enable_dns_hostnames: true
  enable_dns_support: true

public_subnets:
  - cidr: "10.35.1.0/24"
    availability_zone: "us-east-1a"
  - cidr: "10.35.2.0/24"
    availability_zone: "us-east-1b"

private_subnets:
  - cidr: "10.35.3.0/24"
    availability_zone: "us-east-1a"
  - cidr: "10.35.4.0/24"
    availability_zone: "us-east-1b"

nat_gateway:
  enable: true
  create_eip: true

# Autoscaling, LaunchTemplate and EC2 Settings
autoscaling:
  desired_capacity: 2
  max_size: 4
  min_size: 1

launch_template:
  name: "webserver-lt"
  instance_name: "Webserver"
  instance_type: "t4g.nano"

  ebs:
    device_name: "/dev/sda1"
    volume_type: "gp3"
    volume_size: 8
    delete_on_termination: true
    encrypted: true

  network_interfaces:
    associate_public_ip_address: false

  user_data_script: | 
    #!/bin/bash
    # Webserver Cloud Init Script
    
    sudo dnf update -y
    sudo dnf install -y nginx
    echo "<h1>Welcome to $(hostname -f)</h1>" | sudo tee /usr/share/nginx/html/index.html
    sudo systemctl start nginx
    sudo systemctl enable nginx
    echo "Done!"

# ALB and Target Group Settings
load_balancer:
  name: "webserver-alb"
  internal: false

target_group:
  name: "webserver-tg"
  port: 80
  protocol: "HTTP"
