name: Deploy to AWS

on:
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      # If needed, also set AWS_DEFAULT_REGION
      AWS_DEFAULT_REGION: 'us-east-1'
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: '1.2.0'

    - name: Terraform Format
      id: fmt
      run: terraform fmt -check

    - name: Terraform Init
      id: init
      run: terraform init

    - name: Terraform Validate
      id: validate
      run: terraform validate

    - name: Terraform Plan
      id: plan
      run: terraform plan

    # Optional: Apply step, be cautious with automated apply in CI/CD pipelines
    # - name: Terraform Apply
    #   if: github.ref == 'refs/heads/main' && github.event_name == 'pull_request'
    #   run: terraform apply -auto-approve
